DROP TABLE IF EXISTS R;
CREATE TABLE R (
    a INTEGER NOT NULL, 
    b INTEGER NOT NULL, 
    c INTEGER NOT NULL
);

LOAD DATA LOCAL INFILE '/Users/jene/abc.csv' INTO TABLE R
    FIELDS TERMINATED BY ',' 
    LINES TERMINATED BY '\r\n'
    IGNORE 1 LINES;